import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  docSidebar: [
    {
      type: 'category',
      label: 'Overview',
      items: [{ type: 'autogenerated', dirName: 'overview' }],
    },
    {
      type: 'category',
      label: 'Usage',
      items: [{ type: 'autogenerated', dirName: 'usage' }],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [{ type: 'autogenerated', dirName: 'advanced' }],
    },
    {
      type: 'category',
      label: 'Examples',
      items: [{ type: 'autogenerated', dirName: 'examples' }],
    },
    {
      type: 'category',
      label: 'Migration',
      items: [{ type: 'autogenerated', dirName: 'migration' }],
    },
    {
      type: 'doc',
      id: 'api',
    },
    {
      type: 'doc',
      id: 'troubleshooting',
    },
  ],
};

export default sidebars;
