import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  docSidebar: [
    {
      type: 'category',
      label: 'Overview',
      items: [{ type: 'autogenerated', dirName: 'overview' }],
    },
    {
      type: 'category',
      label: 'Usage',
      link: {
        type: 'generated-index',
        title: 'Usage',
        description:
          'How to install, configure and use the global exception handler in your app.',
        slug: '/usage',
        keywords: ['usage', 'install', 'configuration'],
        image: '/img/logo-full-light.svg',
      },
      items: [{ type: 'autogenerated', dirName: 'usage' }],
    },
    {
      type: 'category',
      label: 'Advanced',
      link: {
        type: 'generated-index',
        title: 'Advanced',
        description: 'Advanced topics and integrations for power users.',
        slug: '/advanced',
        keywords: ['advanced', 'integration', 'customization'],
        image: '/img/logo-full-light.svg',
      },
      items: [{ type: 'autogenerated', dirName: 'advanced' }],
    },
    {
      type: 'category',
      label: 'Examples',
      link: {
        type: 'generated-index',
        title: 'Examples',
        description:
          'Example projects and code snippets showing typical usage patterns.',
        slug: '/examples',
        keywords: ['examples', 'snippets', 'samples'],
        image: '/img/logo-full-light.svg',
      },
      items: [{ type: 'autogenerated', dirName: 'examples' }],
    },
    {
      type: 'category',
      label: 'Migration',
      link: {
        type: 'generated-index',
        title: 'Migration',
        description:
          'Notes and instructions for upgrading between major versions.',
        slug: '/migration',
        keywords: ['migration', 'upgrade', 'breaking-changes'],
        image: '/img/logo-full-light.svg',
      },
      items: [{ type: 'autogenerated', dirName: 'migration' }],
    },
    {
      type: 'doc',
      id: 'api',
    },
    {
      type: 'doc',
      id: 'troubleshooting',
    },
  ],
};

export default sidebars;
